general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 14

[window]
padding.x = 0
padding.y = 0
decorations = "None"
opacity = 1

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
